function writetraj(fn, fit, frames, typefile, detoptions, handles)
% function writetraj(fn, fit, frames, typefile, detoptions, handles)
% creates .traj files from data generated by initial tracking
% updates .traj files with data from .con.trc files
%
% MR mar 09 - for SPTrack v4
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% parameters & definitions
datapath=['traj\'];
[namefile,rem]=strtok(fn,'.'); %sin extension
current_dir=cd;
trajfile=[namefile,'.traj'];

%typefile=0;

if typefile==0 % sin reconectar: crea archivo
    
   % structure source
   source.chemin=[cd,'\',datapath];
   source.fichier=fn;
   %prov='mock';
   information.Te=detoptions(17);
   recadrage.Nz = frames; 
   % structure parametres
   parametres.physiques.NA = detoptions(23);
   parametres.physiques.lambda = detoptions(24); %wavelenght
   parametres.physiques.a = detoptions(18);
   parametres.physiques.Te = detoptions(17);
   parametres.tracking.persistance = detoptions(15);
   parametres.tracking.Dini = detoptions(16);
   fond='mock';
   nb_fits=1;
   nofit='mock';
   % saves .traj
   if isdir(datapath); else; mkdir(datapath); end;
   save([datapath,trajfile],'source','information','recadrage','parametres','fond','nb_fits','nofit','fit','-mat');
   disp(['File ',trajfile,' saved in ',datapath])
   disp([ ]);

elseif typefile==1  %ya hay archivo
    
    if isdir(datapath); else; mkdir(datapath); end 
        
    cd(datapath);
    k = strfind('.traj', namefile);
    if isempty(k)==1
          fn=[namefile,'.traj'];
          trcfilename=['trc\',namefile,'.con.trc'];
    end
   % nb_fits=1;
   % fit(nb_fits)=fit;
    %fit(nb_fits).new_spot=nuevo  ;
    
    cd(current_dir);
    nuevo=creastruct(trcfilename);
    cd(datapath);
    
    if length(dir(fn))>0
       load([datapath,fn],'-mat');
       fit.new_spot=nuevo  ;

    else
        cd(current_dir);
        % mock (simulations)
        x=load(trcfilename);
        source.chemin=[cd,'\',datapath];
        source.fichier=fn;
        information.Te=75;
        %information.Te=detoptions(17);
       % recadrage.Nz = frames; 
        
        parametres.physiques.NA = 1.45;
        parametres.physiques.lambda = 655; %wavelenght
        parametres.physiques.a = 190;
        parametres.physiques.Te = 75;
        parametres.tracking.persistance = 5;
        parametres.tracking.Dini = 0.04;
%%%%%
       % source.chemin=[];
       % source.fichier=fn;
      %  information.Te=1;
        recadrage.Nz = max(x(:,2)); 
        % structure parametres
      %  parametres.physiques.a = 1;
      %  parametres.physiques.Te = 1;
      
        fond=[];
        nb_fits=1;
        nofit=[];
        fit.new_spot=nuevo  ;
        fit.spot=nuevo  ;
    end
    cd(current_dir);
    % saves .traj
    save([datapath,fn],'source','information','recadrage','parametres','fond','nb_fits','nofit','fit','-mat');
    disp(['File ',fn,' saved in ',datapath])
    disp([ ]);
end


   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%